### ISSUE TITLE
fails to build with text-2.1.2

### ISSUE THREAD

**Issue by juhp** [codedownio/myers-diff#13]
For Stackage Nightly with ghc-9.10.2

```
       Building library for myers-diff-0.3.0.0...                                                             12:58:25 [5772/954403]
       [1 of 3] Compiling Data.Diff.Types                                                                                           
       [2 of 3] Compiling Data.Diff.Myers                                                                                           
       /home/curators/work/unpack-dir/unpacked/myers-diff-0.3.0.0-d5df3f3db9fb5f7f07b629f76d68655849d04a9395cfea0ead4d6a9ed229eb0b/s
rc/Data/Diff/Myers.hs:190:23: error: [GHC-87543]                                                                                    
           Ambiguous occurrence ‘Empty’.                                                                                            
           It could refer to                                                                                                                      either ‘Seq.Empty’,                                                                                                   
                     imported from ‘Data.Sequence’ at src/Data/Diff/Myers.hs:50:1-27                                                
                     (and originally defined in ‘Data.Sequence.Internal’),                                                          
                  or ‘T.Empty’,                                                                                                     
                     imported from ‘Data.Text’ at src/Data/Diff/Myers.hs:51:1-21.                                                   
           |                                                                                                                        
       190 |     go seqSoFar _ _ _ Empty = seqSoFar                                                                                 
           |                       ^^^^^
```

**Comment by thomasjm** [comment]
Fixed and released as `0.3.0.1`

**Comment by alaendle** [comment]
@thomasjm - think you forgot to also adapt the test cases in `0.3.0.1`

**Comment by thomasjm** [comment]
Oops -- fixed and released as `0.3.0.2`.
